apiVersion: v1
kind: Service
metadata:
  name: my-angular-app-service-load-balancer
spec:
  selector:
    app: my-angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
